#!/bin/sh

install_dir(){ mkdir -p "$2"; cp -rv "$1" "$2"; }
remove(){ [ -e "$1" ] && rm -vrf --preserve-root "$1"; }

[ -z "$DESTDIR" ] && DESTDIR=/
[ -z "$PREFIX" ] && PREFIX=/usr
_PREFIX=${DESTDIR%%/}/${PREFIX##/}

[ ! -w "$DESTDIR" ] && echo "You don't have write access on $DESTDIR" && exit 1

progname=feed-push
confdir="${DESTDIR}etc/$progname"

case "$1" in
	install)
		install -v -m 755 -D $progname "$_PREFIX/bin/$progname"
		install_dir examples "$_PREFIX/share/$progname"
		install -vd "$confdir"
		install -v -m 644 -D init/$progname.service "${DESTDIR}usr/lib/systemd/system/$progname.service"
		;;
	uninstall)
		remove "$_PREFIX/bin/$progname"
		remove "$_PREFIX/share/$progname/examples"
		if [ $(ls -a "$confdir" | wc -l) -eq 2 ]; then rmdir "$confdir"
		else echo "not removing config dir $confdir (not empty)"
		fi
		;;
	update)
		$0 uninstall &>/dev/null
		$0 install
		;;
	*)
		echo "usage: [DESTDIR=/] [PREFIX=/usr] $(basename "$0") install|uninstall|update" && exit 1
		;;
esac

exit 0
